In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
arr = [1,2]

tensor = torch.tensor(arr)
val = 2.0
tensor2 = torch.tensor(val)

In [4]:
print(tensor)
print(tensor2)

tensor([1, 2])
tensor(2.)


In [6]:
import numpy as np 

npArr = np.array([1,2])

x_t = torch.from_numpy(npArr)

print(x_t)

tensor([1, 2])


In [8]:
#  Using the endpoints to inititalize a tensor/ create them

zeros_t = str(torch.zeros((2,3)))
ones_t = str(torch.ones((2,3)))
rand_t = str(torch.rand((2,3)))

print(zeros_t + "\n" + ones_t + "\n" + rand_t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4606, 0.7370, 0.0306],
        [0.1884, 0.8246, 0.4247]])


In [12]:
arr = [1,2]

x_t = torch.tensor(arr, dtype=torch.float16)

x_t.dtype

torch.float16

In [13]:
x_t.device

device(type='cpu')

In [14]:
device = 'cuda'

In [17]:
arr = [1,2]

x_t = torch.tensor(arr, device=device)
x_t.device

device(type='cuda', index=0)

In [19]:
x1_t = torch.tensor([[1,2], [3,4]])
x2_t = torch.tensor([[1,2,3], [4,5,6]])

torch.matmul(x1_t, x2_t)

tensor([[ 9, 12, 15],
        [19, 26, 33]])

In [26]:
i,j,k = 0,0,0
x3_t = torch.tensor([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])



print(x3_t)


x3_t[i,j,k]


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


tensor(1)

In [ ]:
x3_t[:1,0:2,2:]


device(type='cpu')

In [35]:
#  testing the partial derivative of a particular function

x = torch.tensor(2.0, requires_grad= True)
y = torch.tensor(3.0, requires_grad= True)
z = torch.tensor(4.0, requires_grad= True)

f = x**3+ y**2 + z**2

f.backward()
x.grad, y.grad, z.grad

(tensor(12.), tensor(6.), tensor(8.))

In [45]:
import torch.nn as nn

inDim, outDim = 256, 10

vec = torch.randn(256, device= device)

layer = nn.Linear(inDim, outDim, bias= True).to(device=device)

# or 

layer2 = nn.Linear(inDim, outDim, bias= True, device=device)



out = layer(vec)

print(out)


tensor([-1.0842,  0.0952,  0.3773,  0.1896, -0.2977,  0.1079, -0.9554,  0.3491,
        -0.0389,  0.4262], device='cuda:0', grad_fn=<ViewBackward0>)


In [46]:

W = torch.rand(10, 256).to(device= device)
b = torch.zeros(10,1).to(device = device)
out = torch.matmul(W, vec) + b

print(out)

tensor([[ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765, -13.6387, -16.2250, -10.2438,
          -6.7481,  -6.6803,  -8.8739],
        [ -7.0588, -16.0302,  -6.7622, -11.2765,

In [53]:
inDim = 784
featureDim = 256
outDim = 10

vec = torch.randn(784, device=device)

layer1 = nn.Linear(inDim, featureDim,device=device, bias=True)
layer2 = nn.Linear(featureDim, outDim, device=device, bias=True)

out = (layer2(layer1(vec)))

print(out)
print(vec.shape)
# print(featureDim.shape)

tensor([ 0.5482, -0.4530,  0.8699,  0.5268, -0.0127, -0.1982,  0.1374,  0.4818,
        -0.1659, -0.7033], device='cuda:0', grad_fn=<ViewBackward0>)
torch.Size([784])


In [54]:
# non linear neuron

relu = nn.ReLU()

out = layer2(relu(layer1(vec)))

print(out)

tensor([ 0.2913, -0.3113,  0.6609,  0.2966,  0.2987,  0.0993, -0.1401,  0.0969,
         0.1110, -0.2947], device='cuda:0', grad_fn=<ViewBackward0>)
